name: pln
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.9.0
  - astor=0.8.0
  - blas=1.0
  - blinker=1.4
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - gast=0.2.2
  - google-auth=1.14.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - idna=2.9
  - intel-openmp=2020.1
  - joblib=0.14.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libprotobuf=3.11.4
  - markdown=3.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nltk=3.4.5
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pip=20.0.2
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.10
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - tqdm=4.46.0
  - urllib3=1.25.8
  - werkzeug=0.16.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - zlib=1.2.11
  - pip:
    - ipython-genutils==0.2.0
    - tornado==6.0.4
    - traitlets==4.3.3